version: '3.8'

services:
  queue_middleware:
    container_name: queue_middleware
    image: rabbitmq:management
    restart: unless-stopped
    ports:
        - 15672:15672
    networks:
      - stack-overflow-analysis

  coordinator-1:
    container_name: coordinator_1
    build: .
    env_file:
      - coordinator.env
    environment:
      - NODE_ID=1
    volumes: &coordinator-volumes
      - ./state.txt:/app/state.txt
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: main.py
    networks:
      - stack-overflow-analysis

  coordinator-2:
    container_name: coordinator_2
    build: .
    env_file:
      - coordinator.env
    environment:
      - NODE_ID=2
    volumes: *coordinator-volumes
    entrypoint: ["./wait-for", "coordinator-1:9000", "--", "python"]
    command: main.py
    networks:
      - stack-overflow-analysis

  coordinator-3:
    container_name: coordinator_3
    build: .
    env_file:
      - coordinator.env
    environment:
      - NODE_ID=3
    entrypoint: ["./wait-for", "coordinator-2:9000", "--", "python"]
    command: main.py
    volumes: *coordinator-volumes
    networks:
      - stack-overflow-analysis

  vault_1:
    container_name: vault_1
    build: .
    env_file:
      - vault.env
    environment:
      - NODE_ID=1
    command: main-vault.py
    volumes:
      - .:/app
      - ./storage/vault-1:/storage
    networks:
      - stack-overflow-analysis

  vault_2:
    container_name: vault_2
    build: .
    env_file:
      - vault.env
    environment:
      - NODE_ID=2
    entrypoint: ["./wait-for", "vault_1:9000", "--", "python"]
    command: main-vault.py
    volumes:
      - .:/app
      - ./storage/vault-2:/storage
    networks:
      - stack-overflow-analysis

  vault_3:
    container_name: vault_3
    build: .
    env_file:
      - vault.env
    environment:
      - NODE_ID=3
    entrypoint: ["./wait-for", "vault_2:9000", "--", "python"]
    command: main-vault.py
    volumes:
      - .:/app
      - ./storage/vault-3:/storage
    networks:
      - stack-overflow-analysis


  vault-playground:
    build: .
    volumes:
      - .:/app
    networks:
      - stack-overflow-analysis

  heartbeat_1:
    build: .
    env_file:
      - coordinator.env
    volumes: &heartbeat-volumes
      - .:/app
    entrypoint: python3 heartbeat/main.py
    networks:
      - stack-overflow-analysis

  heartbeat_2:
    build: .
    env_file:
      - coordinator.env
    volumes: *heartbeat-volumes
    entrypoint: python3 heartbeat/main.py
    networks:
      - stack-overflow-analysis

  heartbeat_3:
    build: .
    env_file:
      - coordinator.env
    volumes: *heartbeat-volumes
    entrypoint: python3 heartbeat/main.py
    networks:
      - stack-overflow-analysis

  heartbeat_4:
    build: .
    env_file:
      - coordinator.env
    volumes: *heartbeat-volumes
    entrypoint: python3 heartbeat/main.py
    networks:
      - stack-overflow-analysis


networks:
  stack-overflow-analysis:
    ipam:
      driver: default
      config:
        - subnet: 172.25.210.0/24
