version: '3.8'
services:
  app1:
    container_name: app1
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=1
    volumes:
      - ./state.txt:/app/state.txt
      # - ./app/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: python3 test_bully.py
    networks:
      - bully-example
  
  app2:
    container_name: app2
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=2
    volumes:
      - ./state.txt:/app/state.txt
      # - ./app/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["./wait-for", "app1:9000", "--", "python", "test_bully.py"]
    networks:
      - bully-example
  
  app3:
    container_name: app3
    build: .
    env_file:
      - .env
    environment:
      - NODE_ID=3
    volumes:
      - ./state.txt:/app/state.txt
      # - ./app/:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["./wait-for", "app2:9000", "--", "python", "test_bully.py"]
    networks:
      - bully-example

      
  heartbeat_1:
    build: .
    env_file:
      - .env
    # volumes:
      # - ./app/:/app
    entrypoint: python3 heartbeat/main.py
    networks:
      - bully-example

        
  heartbeat_2:
    build: .
    env_file:
      - .env
    # volumes:
      # - ./app/:/app
    entrypoint: python3 heartbeat/main.py
    networks:
      - bully-example



networks:
  bully-example:
    ipam:
      driver: default
      config:
        - subnet: 172.25.210.0/24