version: '3.8'
services:
  app1:
    container_name: app1
    image: bully-example:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LISTEN_PORT=9000
      - PEER_ADDRESS=app2:9001,app3:9002
      - LEADER=True
    ports:
      - 9000:9000
    entrypoint: python3 main.py
    networks:
      - bully-example

  app2:
    container_name: app2
    image: bully-example:latest
    environment:
      - LEADER_ADDRESS=app1
      - PYTHONUNBUFFERED=1
      - LISTEN_PORT=9001
      - PEER_ADDRESS=app1:9000,app3:9002
    command: ["./wait-for", "app1:9000", "--", "python", "main.py"]
    networks:
      - bully-example

  app3:
    container_name: app3
    image: bully-example:latest
    environment:
      - LEADER_ADDRESS=app1
      - PYTHONUNBUFFERED=1
      - LISTEN_PORT=9002
      - PEER_ADDRESS=app1:9000,app2:9001
    command: ["./wait-for", "app2:9001", "--", "python", "main.py"]
    networks:
      - bully-example

networks:
  bully-example:
    ipam:
      driver: default
      config:
        - subnet: 172.25.210.0/24
